### ISSUE TITLE
Fixing problem with alphabetization

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [brandonminch/grunt-prettysass#3]
First of all, great module!
I have a problem when I activate alphabetization with scss files which are structured like that: 

``` scss
#page {
position: relative;
.next, 
.prev {
width: 100;
}
}
```

When i run prettysass over this code, I get the following output: 

``` scss
#page {
.next, 
position: relative;
.prev {
width: 100;
}
}
```

So it seems that if you use a new line for each class or id, the module thinks it is an attribute and sorts it. It have no problems with classes and ids in one line. 

Would be great if you can take a look.
